name = "watermarknt"
main = "src/index.js"
compatibility_date = "2024-06-10"

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true
head_sampling_rate = 1
# Head-based sampling rate (0-1): 1 = 100% of requests logged
# Lower values like 0.1 = 10% sampling for high-traffic apps

[observability.logging]
enabled = true
# Include invocation logs with request/response metadata